#ifndef COLOR_LIB_H
#define COLOR_LIB_H

//asembler output
#define COLOR_BLUE          "\033[0;34m"
#define COLOR_SKY_BLUE      "\033[38;5;117m"
#define COLOR_BLUE_BRIGHT   "\033[0;94m"
#define COLOR_ROYAL_BLUE    "\033[38;5;63m"
#define COLOR_DARK_BLUE     "\033[38;5;18m"
#define COLOR_RESET         "\033[0m"

#define BLUE(STR)           COLOR_BLUE STR COLOR_RESET  
#define SKY_BLUE(STR)       COLOR_SKY_BLUE STR COLOR_RESET
#define BLUE_BRIGHT(STR)    COLOR_BLUE_BRIGHT STR COLOR_RESET
#define ROYAL_BLUE(STR)     COLOR_ROYAL_BLUE STR COLOR_RESET
#define DARK_BLUE(STR)      COLOR_DARK_BLUE STR COLOR_RESET

//metki output
#define COLOR_GOLDEN_YELLOW   "\033[38;5;220m"  
#define COLOR_YANTAR          "\033[38;5;214m"  
#define COLOR_LIGHT_YELLOW    "\033[38;5;229m"  

#define LIGHT_YELLOW(STR)     COLOR_LIGHT_YELLOW STR COLOR_RESET
#define GOLDEN_YELLOW(STR)    COLOR_GOLDEN_YELLOW STR COLOR_RESET
#define YANTAR(STR)           COLOR_YANTAR STR COLOR_RESET

#endif //COLOR_LIB_H